name: Pipeline do chuchu
on:
  pull_request:
    branches:
      - development
    paths-ignore:
      - README.md

jobs:
  chuchu:
    name: "My very first job"
    runs-on: ubuntu-latest
    steps:
      - name: Running test01
        run: echo "Opa, blz ? Parece que boa hein ?!"
      - name: Getting the code
        uses: actions/checkout@v2
      - name: Setup ruby
        uses: ruby/setup-ruby@v1
      - name: Install rubocop
        run: gem install bundler rubocop-rails rubocop
      - name: Run Rubocop
        run: rubocop

  # ---------------------------------------- #
  # Building application  
  # ---------------------------------------- #
  buid_n_package:
    name:  Build and Package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: short-sha
        id: short-sha
        run:
          echo "::set-output name=sha::$(echo "${{ env.ghub_sha }}" | cut -c1-8)"
      - name: Build image
        uses: elgohr/Publish-Docker-Github-Action@master
        id: build
        with:
          name: solvis-engineering/${{ env.app_name }}/${{ env.app_name }}
          tags: ${{ steps.short-sha.outputs.sha }}
          dockerfile: Dockerfile

  
  
